name: Mirror to Another Repository

on:
  push:
    branches:
      - main  # change this if your default branch is different

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Anish Menon"
          git config --global user.email "anishkmenon@gmail.com"

      - name: Push to mirror repo
        env:
          TARGET_REPO: https://${{ secrets.MIRROR_TOKEN }}@github.com/anishkmenon/anishkmenon.github.io.git
        run: |
          git remote add mirror $TARGET_REPO
          git push --force mirror HEAD:main
